### PR TITLE
Update ethnicity groupings with TB's corrections

### PR DESCRIPTION
**Pull request by turambar**
TB recommends the slightly more precise ethnicity groupings. I'm inclined to agree, modulo concerns about the sizes of groups 5 and 6:

```
e_map = {'ASIAN': 1,
         'BLACK': 2,
         'CARIBBEAN ISLAND': 2,
         'HISPANIC': 3,
         'SOUTH AMERICAN': 3,
         'WHITE': 4,
         'MIDDLE EASTERN': 4,
         'PORTUGUESE': 4,
         'AMERICAN INDIAN': 5,
         'NATIVE HAWAIIAN': 6,
         'UNABLE TO OBTAIN': 0,
         'PATIENT DECLINED TO ANSWER': 0,
         'UNKNOWN': 0,
         '': 0}
```

### CODE REVIEW

**Comment by turambar** [comment]
See https://github.com/YerevaNN/mimic3-benchmarks/issues/27

**Comment by turambar** [comment]
The PR now has the following map:

```
e_map = {'ASIAN': 1,
         'BLACK': 2,
         'CARIBBEAN ISLAND': 2,
         'HISPANIC': 3,
         'SOUTH AMERICAN': 3,
         'WHITE': 4,
         'MIDDLE EASTERN': 4,
         'PORTUGUESE': 4,
         'AMERICAN INDIAN': 5,
         'NATIVE HAWAIIAN': 6,
         'UNABLE TO OBTAIN': 0,
         'PATIENT DECLINED TO ANSWER': 0,
         'UNKNOWN': 0,
         '': 0}
```

**Comment by turambar** [comment]
@Harhro94 Now that the 1.0 release is done, should one of us should review this and then make the merge?

**Comment by Harhro94** [comment]
The final map looks good ! I will merge this.

**Pull request merged**
