### PR TITLE
Use iloc and rename instead of ix and reanme_axis

### PR DESCRIPTION
**Pull request by arunachalamb**
Replace deprecated interfaces in pandas by substiuting .iloc to index
instead of .ix and replace .rename(columns=...) instead of
.rename_axis(axis=1,...).

Fixed a couple of issues causing runtime errors with pandas 0.25.3 and
python 3.7.

### CODE REVIEW

**Comment by nanara1119** [comment]
is correct to change ix to iloc in mimic3csv.py?

in my case more error occur ...

(python 3.7, pandas 0.25.3 )

**Comment by hrayrhar** [comment]
Hi @arunachalamb ,

Thanks for interest in improving the code. I just reviewed the code, and it seems that in almost all cases we can replace `.ix` with `.loc`. Replacing with `.iloc` will be wrong, as almost always we work with data frame indices rather than row ids.

I made the changes, now I am running tests to see whether we get the same results.

Hrayr

**Comment by arunachalamb** [comment]
Sounds good.  Thanks for the update.
Best regards,
Babu
    On Thursday, March 26, 2020, 11:21:56 AM PDT, Hrayr Harutyunyan <notifications@github.com> wrote:  
 
 


Hi @arunachalamb ,

Thanks for interest in improving the code. I just reviewed the code, and it seems that in almost all cases we can replace .ix with .loc. Replacing with .iloc will be wrong, as almost always we work with data frame indices rather than row ids.

I made the changes, now I am running tests to see whether we get the same results.

Hrayr

**Comment by hrayrhar** [comment]
Hi @arunachalamb,

The test were successful, so I push the changes. You can view my edits in this [commit](https://github.com/YerevaNN/mimic3-benchmarks/commit/6c00600cac6ddb0d4625d62adb434f02a3c3cc28).

Hrayr

**Pull request closed without merging**
